name: Build and Push Blazor WASM for Hostinger

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Clean Blazor WASM Project
        working-directory: BlazorPortfolio.BlazorWASM
        run: dotnet clean

      - name: Delete previous publish output
        working-directory: BlazorPortfolio.BlazorWASM/bin/Release/net10.0
        run: rm -rf publish

      - name: Publish Blazor WASM
        working-directory: BlazorPortfolio.BlazorWASM
        run: dotnet publish -c Release

      - name: Add timestamp to force diff
        working-directory: BlazorPortfolio.BlazorWASM/bin/Release/net10.0/publish/wwwroot
        run echo "Build: $(date)" > build.txt

      - name: Push publish output to build branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: build
          FOLDER: BlazorPortfolio.BlazorWASM/bin/Release/net10.0/publish/wwwroot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Blazor WASM build: ({sha}) {msg}"
          FORCE: true

