name: Build and Push Blazor WASM for Hostinger

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Publish Blazor WASM
        working-directory: BlazorPortfolio.BlazorWASM
        run: dotnet publish -c Release

      - name: Push publish output to build branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: build
          FOLDER: BlazorPortfolio.BlazorWASM/bin/Release/net10.0/publish
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Blazor WASM build: ({sha}) {msg}"

